DeveloperAcademy-POSTECH/MacC_Team_Beartear

- Gom4ziz/Gom4ziz.xcodeproj/project.pbxproj
- Gom4ziz/Gom4ziz/Data/UserInfoRepository.swift
- Gom4ziz/Gom4ziz/Extension/ProcessInfo.swift
- Gom4ziz/Gom4ziz/Extension/RxSwift+Firestore.swift
🔒 Related to #6 
- Firestore RxSwift Extension 추가했습니다.
- Extension 폴더의 Firestore Extension 만 리뷰하면 될 것 같습니다.
- 일단 Rx Extension 을 추가하는 방법은 너무나 유명하니 아래 레퍼런스 탭을 참고해주세요.
```swift
func document(source: FirestoreSource = .default) -> Observable<DocumentSnapshot> {
Observable.create { observer in
base.getDocument(source: source) { snapshot, error in
guard error == nil else {
observer.onError(error!)
return
}
guard let snapshot, snapshot.exists else {
observer.onError(RxFirestoreError.documentIsNotExist)
return
}
observer.onNext(snapshot)
observer.onCompleted()
}
return Disposables.create()
}
}
```
- 기존 completion handler 를 사용하는 API 를, 위와 같이 Observable 로 바꿀 수 있습니다. (여기서 중요한 것은 꼭!! Observable 의 라이프 사이클에서 onComplete 혹은 onError 를 호출해서 Observable stream 을 종료해주어야 한다는 것입니다.
- 보통 Document Reference 에서 …
> Repository 작업 전 Firestore 에 대한 Rx Extension 을 추가하였습니다.

- .github/workflows/main.yml
- .gitignore
- Gom4ziz/Gom4ziz.xcodeproj/project.pbxproj
- Gom4ziz/Gom4ziz/Resources/Info.plist
- Gom4ziz/Gom4ziz/System/AppDelegate.swift
- Related to #15 
- 카카오 의존성 (Rx Kakao share) 을 추가하고, 카카오 관련 API key 파일 참조를 pbxproj 에 추가하였음.
- REST API Key 는 이그노어에 추가해서, 따로 파일을 공유하는 형식으로 진행하겠음
- kakao native app key는, 어차피 url scheme 에 포함되기 때문에, 굳이 Secret 파일에 추가하지 않았습니다.
- 또한 Secret 폴더에 있는 모든 파일을 이그노어에 추가했는데, 따라서 해당 폴더의 파일들은 모두 로컬로 직접 추가해야 합니다.
- 어떤 식으로 Secret swift file 들을 공유하면 충돌이 안 나고 잘 공유될지가 고민되네요! 해당 **부분내용은 #17 에 존재하며 꼭 필수적으로 읽어주시기 바랍니다!!**
- 없음
- 참고한 이슈에 참고한 링크들이 존재합니다.
> Chore: Add Kakao dependency & secret key

- Gom4ziz/Gom4ziz.xcodeproj/project.pbxproj
- Gom4ziz/Gom4ziz/Data/PlansRoomRepository.swift
- Gom4ziz/Gom4ziz/Domain/Model/PlansRoom.swift
- Gom4ziz/Gom4ziz/Domain/Usecase/JoinPlansRoomUsecase.swift
- Gom4ziz/Gom4ziz/Extension/RxSwift+Firestore.swift
- Gom4ziz/Gom4ziz/System/Deeplink/Deeplink.swift
- Gom4ziz/Gom4ziz/System/Deeplink/DeeplinkHandler.swift
- Gom4ziz/Gom4ziz/System/Deeplink/DeeplinkParser.swift
- Gom4ziz/Gom4ziz/System/SceneDelegate.swift
- Gom4ziz/Gom4zizTests/PlansRoomRepositoryTests.swift
- Gom4ziz/Gom4zizTests/System/DeeplinkParserTests.swift
🔒 Close #21 
- Deeplink 를 처리하는 핸들러 객체 추가
- Deeplink 가 딥링크를 정확히 파싱하는지 테스트하는 코드 추가
- PlansRoom Repository에 약속방 참가하는 함수를 새로 만들었습니다.
- Firebase 에서 필드를 업데이트하는 rx extension 을 추가했습니다.
- [Deeplink가 무슨 타입의 딥링크인지 나타내는 enum 추가](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:feat%2F%2321_deep_link_handling?expand=1&title=21%20%5BFeature%5D%3A%20딥링크를%20타고%20들어와%20약속방에%20참가하는%20기능#diff-17ca64b05841d66669a1e9797a890677194e6d0c65c28130cf673bd21d794ffcR10-R30)
- [url 을 가지고 Deeplink type 을 반환하는 DeeplinkParser 를 추가했습니다.](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:feat%2F%2321_deep_link_handling?expand=1&title=21%20%5BFeature%5D%3A%20딥링크를%20타고%20들어와%20약속방에%20참가하는%20기능#diff-6da4b9daf24eeb1b …
> [Feature]: 딥링크를 타고 들어와 약속방에 참가하는 기능

- Gom4ziz/.swiftlint.yml
- Gom4ziz/Gom4ziz.xcodeproj/project.pbxproj
- Gom4ziz/Gom4ziz/Domain/Model/UserInfo.swift
- Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginManager.swift
- Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginView.swift
- Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
- Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewModel.swift
- Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/LoginManagerProtocol.swift
- Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/LoginViewModel.swift
- Gom4ziz/Gom4ziz/Resources/Base.lproj/Main.storyboard
- Gom4ziz/Gom4ziz/System/SceneDelegate.swift
🔒 Close #13
[호종이 리뷰](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/28)보고 ViewModel에서 도메인 로직을 구현하지 않고 Usecase(Manager)에 필요한 함수를 호출하도록 구조를 수정했습니다.
- LoginManagerProtocol 프로퍼티에 다음과 같은 변수를 필요로 한다고 코드를 짜서 KakaoLoginManager에 해당 프로퍼티가 있는데, KakaoLoginManager가 아닌 ViewModel에 해당 값이 있어야 하는 건지 잘 모르겠습니다. 
```
var userInfo: PublishRelay<UserInfo> { get }
var loginstatus: PublishRelay<Loginstatus> { get }
```
- ~~@HoJongE 제가 카카오 네이티브 앱을 만들었었는데, 호종이께서 네이티브 앱을 만들어 팀원을 초대하셨더라구요! 그걸로 이동하겠습니다! 확인하시면 댓글 남겨주세요~~ -> 네이티브 앱 호종이 껄로 이동 후에 [세부 내용 설정](https://developers.kakao.com/console/app)했습니다.
- ~~로그인 시 사용자에게 Client가 "닉네임과 프로필 사진" 접근을 허용할 것인지 물어봅니다. 이 접근 허용 필수 선택으로 변경할까요?~~ -> 우선 선택 허용으로 두겠습니다.
- 1. …
> feat: KaKao Login, Logout, unLink testUI 작성

- Gom4ziz/Gom4ziz.xcodeproj/project.pbxproj
- Gom4ziz/Gom4ziz/Presenter/ShareTest/ShareTestView.swift
- Gom4ziz/Gom4ziz/Presenter/ShareTest/ShareTestViewController.swift
- Gom4ziz/Gom4ziz/Utility/AutoLayoutUIView.swift
- Gom4ziz/Gom4ziz/Utility/Loadable.swift
- Gom4ziz/Gom4ziz/Utility/RxViewController.swift
- **BaseRxViewController** 추가 -> ViewModel 혹은 다른 Observable 의 구독을 설정하는 setUpObserver 함수 추가 및 자동으로 호출하게 해놓음 (프로토콜이라 구현만 하면 됨)
- **BaseAutoLayoutUIView** 추가  -> 자식 뷰들을 추가하고, 제약조건을 거는 함수들을 추가. 그리고 해당 함수들을 자동으로 호출한다. 마찬가지로 protocol 이라서 구현만 하면 됨
- 비동기적으로 가져오는 타입의 데이터와 상태를 한 번에 나타낼 수 있는 **Loadable enumeration** 추가
- [BaseAutoLayoutUIView 를 사용하는 방법](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:Feat%2F_add_utility_codes?expand=1&title=Feat%3A%20Add%20Utility%20code%20to%20share%20&body=%23%23%20Close%20Issues%0A-%20Pull%20Request와%20관련된%20Issue가%20있다면%20나열합니다.%0A%F0%9F%94%92%20Close%20%23number%0A%0A%23%23%20작업%20내용%20(Content)%0A-%20작업한%20내용을%20나열%20후%20설명%0A%0A%23%23%20Review%20points%0A-%20리뷰어가%20중점적으로%20리뷰해줬으면%20하는%20포인트%0A%0A%23%23% …
> Feat: Add Utility code to share 

- Gom4ziz/Source/Presenter/WeeklyArtworkStatus.swift
🔒 Close #65
기존의 Loadable로는 artwork 요청에 대한 상태를 나타내지 못하는 경우가 있어 새로운 데이터타입을 정의하였습니다.
ex. 모든 질문들에 답하여 이번주 토요일까지 받아올 artwork가 없는 경우
앱 내의 다양한 경우에서 artwork를 불러올 일이 있을 것으로 보이나, 이러한 artwork 요청에 대한 특이한 상태는 질문관련 로직 구현에만 사용될 것 이라는 판단이 들었습니다.
그래서 enum을 generic으로 만들지 않고 WeeklyArtworkStatus 라고 명명했습니다.
- [링크이름](링크)
> Feat: artwork 요청에 대한 상태를 나타내기 위한 데이터타입을 정의하였습니다.

- Gom4ziz/Source/Data/FirebaseArtworkRepository.swift
- Gom4ziz/Source/Data/Repository/FirebaseArtworkReviewRepository.swift
- Gom4ziz/Source/Domain/Model/MockData.swift
- Gom4ziz/Source/Extension/RxSwift+Firestore.swift
- Gom4zizTests/Source/ArtworkReviewRepositoryTests.swift
- Gom4zizTests/Source/Extension/FirebaseArtworkRepositoryExtension.swift
- Gom4zizTests/Source/Extension/FirebaseArtworkReviewRepositoryExtension.swift
🔒 Close #67 
- [Firebase Transaction의 Rx Extension을 추가하였습니다.](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:Feature%2F%2367_add_artworkReview?expand=1#diff-b8e8eca85dc0baa2c703fb72f3b5f16258cd7cc0a98f11929f97f515d1156011R108-R122)
- [Transaction을 사용하여, artworkReview와 user의 lastArtworkId 속성을 업데이트 하는 기능을 구현했습니다.](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:Feature%2F%2367_add_artworkReview?expand=1#diff-a1330d7a1fd82d706abb958f4b14dce494bc60c271ef1112fefc408dec87fce0R32-R53)
- [ArtworkReviewRepository Test를 쉽게 하기 위한 extension 코드들을 Test target에 추가하였습니다.실제 프로덕트에서는 artwork를 가내수공업으로 제작하므로, artwork를추가, 삭제하는 코드를 추가했습니다.](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Bea …
> Feature #67 ArtworkReview를 추가하는 기능을 구현했습니다.

- Gom4ziz/Source/Domain/Model/MockData.swift
- Gom4ziz/Source/Domain/UseCase/FetchArtworkReviewUseCase.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewModel.swift
🔒 Close #60 
- <img width="674" alt="Screenshot 2022-11-21 at 20 30 26" src="https://user-images.githubusercontent.com/59136391/203040191-2ccb7f77-6e98-4316-8a16-a910e241e31f.png">
- <img width="591" alt="Screenshot 2022-11-21 at 20 30 00" src="https://user-images.githubusercontent.com/59136391/203039990-2a28d7a4-0ca3-4fb1-8135-88c817d5d072.png">
- ArtworkReview를 불러오는 Domain Logic에 필요한 ArtworkReviewRepository를 의존하는 UseCase 모델을 만들었습니다.
- ArtworkReview를 불러오는 UseCase 모델을 가지는 MyFeedViewModel을 만들었습니다.
- 데이터 요청의 결과에 따른 UI 업데이트를 위해 Loadable로 ArtworkReview를 wrapping 하여 분기처리했습니다.
- 해당 페이지는 무조건 유저의 접근이 필요합니다. BehaviorRelay를 사용해서 초기값을 `.isLoading(last: nil)`로 설정했고, `fetchArtworkReview`를 호출해서 데이터 요청 결과에 따라 `.loaded`, `.failed`로 나누었습니다. …
> Feature: #60 ArtworkReview를 불러오는 Domain 로직을 추가했습니다.

- Gom4ziz/Source/Domain/UseCase/FetchHighlightUseCase.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewModel.swift
🔒 Close #85 
- Highlight를 불러오는 Domain Logic에 필요한 Highlight Repository를 의존하는 UseCase 모델을 만들었습니다.
- Highlight를 불러오는 UseCase 모델을 가지는 MyFeedViewModel을 만들었습니다.
- 데이터 요청의 결과에 따른 UI 업데이트를 위해 Loadable로 Highlight를 wrapping 하여 분기처리했습니다.
- 해당 페이지는 무조건 유저의 접근이 필요합니다. BehaviorRelay를 사용해서 초기값을 .notRequested로 설정했고, fetchHighlight를 호출하면 .isLoading(last: nil)로 변견되고 데이터 요청 결과에 따라 .loaded, .failed로 나누었습니다.
- [링크이름](링크)
> [Feature] #85 Highlight를 불러오는 Domain 로직을 추가했습니다.

- Gom4ziz/Source/Domain/Model/MockData.swift
- Gom4ziz/Source/Extension/NSLayoutConstraint.swift
- Gom4ziz/Source/Extension/UIImage+CIFilter.swift
- Gom4ziz/Source/Extension/UIImageView.swift
- Gom4ziz/Source/Presenter/Component/AsyncImageView.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerView.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerViewController.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerViewModel.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionView.swift
- Gom4ziz/Source/Utility/ImageCacheManager.swift
🔒 Close #49 
- Question에 답할 수 있는 UI를 구현했습니다.
- 또한 AsyncImage를 리팩토링했습니다.  
- Image에 적용할 수 있는 필터를 ImageFilterOption enum으로 나타냈으며, 개발자가 AsyncImageView를 생성할 때, 이미지에 어떤 필터를 적용할 것인지 배열로 전달할 수 있습니다.
- [ImageFilterOption](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:Feat%2F%2349_qustion_answer_ui?expand=1&title=49%20%5BFeature%5D%20질문에%20대한%20답변을%20할%20수%20있다.#diff-601ba98f04dbe4b0a6ff3967ee2d134709edf550f8295c529e16c720d3bfcb78R10-R13) 
- [UIView의 intrinsic Size를 결정하기 위해서, UIView subViews 들의 제약조건을 활용했습니다. 이 때, UIView사이즈를 설정하기 위해서는 UILabel의 intrinsicSize를 유지해야 하기 때문에, contentHuggingPriority와, compressionPriority 를 최상으로 설정했습니다.](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/de …
> [Feature] QuestionAnswerView UI 구현

- Gom4ziz/Resource/Assets.xcassets/Gray1.colorset/Contents.json
- Gom4ziz/Resource/Assets.xcassets/Gray3.colorset/Contents.json
- Gom4ziz/Source/Constants/Typography.swift
- Gom4ziz/Source/Extension/UILabel+TextStyle.swift
- Gom4ziz/Source/Extension/UITextView+TextStyle.swift
- Gom4ziz/Source/Presenter/Component/SectionTitleView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
🔒 Close #90
- MyFeedView를 만들어 Artwork, ArtworkReview, ArtworkDescription을 불러와서 유저에게 보여줍니다.
- 자주 사용되는 컴포넌트로 SectionTitleView를 만들었습니다.
- Section의 타이틀과 Divider를 하나로 가지고 있습니다.
- `private lazy var feedSectionTitleView: SectionTitleView = .init(title: "\(artwork.id)번째 티라미술")` 이렇게 사용하면
- <img width="242" alt="Screenshot 2022-11-25 at 10 18 55" src="https://user-images.githubusercontent.com/59136391/203881657-cf04d91c-b53d-4783-9647-5987d76368da.png">
- 피그마에 디자인 시스템 섹션에 Typography를 정리해놨습니다.
- <img width="586" alt="Screenshot 2022-11-25 at 11 08 00" src="https://user-images.githubusercontent.com/59136391/203886016-888f8752-dfab-4dd8-a275-4af2dd7edbb3.png">
- Typography enum을 만들었습니다.
- 디자인 시안에 모든 TextStyle이 적용되어 있으니 UI 구현하실 때 참고하시고, 적용해주시면 됩니다.
- 이 과정을 편하게 하기 …
> [Feature] #90: ArtworkDescription과 ArtworkReview를 불러와 유저에게 보여준다.

- Gom4ziz/Source/Constants/CollectionName.swift
- Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
- Gom4ziz/Source/Domain/UseCase/FetchQuestionAnswerUsecase.swift
🔒 Close #102
- #102 이슈 참고해주세요 !
- #99 이후 lastArtworkId 이전의 questionAnswer들도 DB에서 불러오는 작업이 추가적으로 필요했습니다.
- 그래서 lastArtworkId 이전의 questionAnswer들을 DB에서 불러오는 QuestionAnswerRepository과 FetchQuestionAnswerUsecase을 구현했습니다 ..!
- 하단의 기타 사항 참고
- Artworks의 subCollection, QuestionAnswers에 접근을 해서 가지고 온 questionAnswer을 list 합쳐야 하는 과정에서 어려움이 있었습니다.
Zip이라는 operator를 써서 구현을 했는데, 이게 가장 좋은 방법이었는지 잘 모르겠습니다. 더 좋은 방법이 있다면 알려주세요..!
> [Feature] #102: lastArtworkId 이전의 questionAnswer들을 DB에서 불러온다. 

- Gom4ziz/Source/Constants/Typography.swift
- Gom4ziz/Source/Extension/Color.swift
- Gom4ziz/Source/Extension/UILabel+TextStyle.swift
- Gom4ziz/Source/Extension/UITextView+TextStyle.swift
- Gom4ziz/Source/Presenter/ArtworkIntroduction/ArtworkIntroductionModal.swift
- Gom4ziz/Source/Presenter/Component/BubbleButton.swift
- Gom4ziz/Source/Presenter/Component/HighlightedTextView.swift
- Gom4ziz/Source/Presenter/Component/PlaceholderTextView.swift
- Gom4ziz/Source/Presenter/Component/SectionTitleView.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerView.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionView.swift
- Gom4ziz/Source/System/SceneDelegate.swift
- Typo 관련 Extension을 수정했습니다! 이유는 다음과 같습니다.
1. 같은 타이포라도, 행간이 다른 Label들이 있다.
2. 또한 attributedText를 사용할 경우, 기존 textAlignment 속성은 먹지 않는다. 따라서 AttributedString전용 alignment를 설정할 필요가 있다.
3. 따라서 커닝, 라인스페이싱, 행간, 텍스트 정렬 등의 파라미터를 추가로 받을 수 있도록 API 를 수정했습니다.
예를 들어 위 사진의 Typo 는 **Display3** 이지만, lineHeightMultiple 은 Typo의 값인 1.5가 아닌 1.26 입니다.
- 기존 UI Component들이 Typo 를 적용하도록 리팩토링했습니다.
- 또한 기존 UI Component들을 조금씩 수정했습니다.
- SectionTitleView를 리팩토링했습니다.
- [SectionTitleView 리팩토링](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:Refactor%2FApplying_typography?expand=1#diff-586bf614747f32f165b8efae043dac8f82f332bc53d7c2b1a429155dad565044R12-R35)
- 먼저, UILabel을 화면에 그릴 때 (draw), 아래쪽에 디바이더를 추가합니다!
```swift
super.draw(rect)
let dividerLayer: CALayer = …
```
> Typography 관련 extension 을 수정하고, 기존 컴포넌트에 타이포를 적용했습니다. 또한 SectionTitleView를 리팩토링했습니다.

- Gom4ziz/Source/Constants/ErrorViewMessage.swift
- Gom4ziz/Source/Presenter/Component/ErrorView.swift
🔒 Close #123
- DB에서 데이터를 불러오는데 실패했을 때, 보여줄 ErrorView를 추가했습니다.
- 사용 방법은
```swift
ErrorView(message: .tiramisul, isShowLogo: false) 
```
이런 식으로 사용합니다.
- ErrorView의 message는 정확한 의미전달과 케이스를 분기하기 위해서 ErrorViewMessage enum을 따로 만들었습니다.
- 단순히 작품을 불러오는데 실패했을 경우는 `.artwork`로 처리하고, 그외의 모든 에러케이스는 `.tiramisul`로 처리합니다.
- `isShowLogo` 프로퍼티는 이름 그대로 로고를 보여줄 것인지 말 것인지를 선택하는 프로퍼티입니다.
- 탭하여 다시 불러오는 로직을 구현하실 때는, ViewController에서 rx.tap 로직을 활용해서 관련 데이터를 fetch하는 메서드를 호출하면 될 것입니다.
- [링크이름](링크)
> [Feature] #123: DB에서 데이터를 불러오는데 실패했을 때, 보여줄 ErrorView를 추가했습니다.

- Gom4ziz/Source/Presenter/Main/ReviewedArtworkList/ReviewedArtworkListCellViewModel.swift
- Gom4ziz/Source/Presenter/Main/ReviewedArtworkList/ReviewedArtworkListViewModel.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
🔒 Close #112 
- ReviewedArtworkListViewModel 구현
-> @HoJongE 가 제안해주신 방법대로 구현했습니다. 감사합니다 :)
- Launch Screen.storyboard 건들지도 않았고, xcode 상에서도 diff가 안 뜨는데 값이 달라져 있습니다.. 혹시 이유를 아시는 분이 있을까요 ?
- develop에서 pull 해오니까, MyFeedView에 questionAnswer가 2번 중복되어 파라매터로 들어가 있었습니다. merge하기 전에 확인을 한번 더 하면 좋을 것 같습니다 ☺️
- [zip 관련 디스커션 with @SH0123 ](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/discussions/131)
> [Feat]: 리뷰된 ArtworkList와 QuestionAnswerList를 불러오는 ReviewedArtworkListViewModel 구현

- Gom4ziz/Source/Presenter/QuestionAnswer/ArtworkIntroduction/ArtworkIntroductionViewController.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerPage/QuestionAnswerView.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerPage/QuestionAnswerViewController.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerPage/QuestionAnswerViewModel.swift
- Gom4ziz/Source/System/SceneDelegate.swift
🔒 Close #159 
- QuestionAnswerView에서 ArtworkDescription 로딩에 실패한 경우, ErrorView를 띄우도록 코드를 리팩토링 하였습니다.
- 또한 다음버튼 활성화 여부를 판단하는 stream을 리팩토링해, self참조 없이도 버튼의 활성화 여부를 반응적으로 변경할 수 있습니다.
- 유저의 답변 입력 여부와, artworkDescription 로딩 성공 여부에 따라 다음화면으로 이동하는 버튼의 활성화 여부를 결정합니다.
- 따라서 유저 답변이 변경될 때나, artworkDescription의 로딩 여부가 변경될 때마다, 버튼의 활성화 여부를 변경해야 합니다 -> combineLatest 사용
이번 pr에서, 기존에 map 내부에서 self.viewModel참조에 따른 self 참조가 일어난 코드를, drive를 통해 self 참조를 없앴습니다.
**변경 전 코드**
```swift
questionAnswerView.answerInputTextView
.rx
.text
.compactMap { $0 }
.asDriver(onErrorJustReturn: "")
.drive(onNext: { [unowned self] in
// 만약 유저가 답변을 입력하고, artworkDescription이 존재한다면 다음 버튼이 활성화된다.
if !$0.isEmpty && viewModel.artworkDescription != nil {
enableNextButton()
return
}
// 만약 유저가 답변을 입력하지 않았거나, artworkDescription이 불러와지지 않은 …
```
> Refactor: Fix QuestionAnswerView to show error view when failed to load

- Gom4ziz/Source/Constants/ViewTag.swift
- Gom4ziz/Source/Extension/UIViewController+Loadble.swift
- Gom4ziz/Source/Extension/UIViewController+Lottie.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
- Gom4ziz/Source/Presenter/MyFeed/ZoomableImageViewController.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerPage/QuestionAnswerViewController.swift
🔒 Close #163
- 감상 기록 화면에서 작품 이미지를 탭하면 확대/축소할 수 있도록 구현했습니다.
- MyFeedView에 있는 artworkImageView를 탭했을 때, ZoomableImageViewController로 present 되도록 구현했습니다.
- MyFeedView에서 UI event가 일어나고, UIViewController에서 present가 일어나야 해서 `ZoomableDeleagteProtocol`을 만들어서 delegate 패턴을 활용했습니다.
- UIViewController extension에 있는 setUpErrorView를 `showErrorView`로 변경했습니다.
- ViewTag enum을 만들어서 constants로 만들었습니다.
- [링크이름](링크)
> [Feature] #163: 감상 기록 화면에서 작품 이미지를 탭하면 확대/축소할 수 있도록 구현했습니다.

- Gom4ziz/Source/Constants/ErrorViewMessage.swift
- Gom4ziz/Source/Data/Repository/FirebaseArtworkRepository.swift
- Gom4ziz/Source/Data/Repository/FirebaseArtworkReviewRepository.swift
- Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
- Gom4ziz/Source/Data/Repository/FirebaseUserRepository.swift
- Gom4ziz/Source/Extension/UIViewController+Loadble.swift
- Gom4ziz/Source/Presenter/Component/ErrorView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewModel.swift
- Gom4ziz/Source/Presenter/MyFeed/UpdateReview/UpdateReviewView.swift
- Gom4ziz/Source/Presenter/MyFeed/UpdateReview/UpdateReviewViewController.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerPage/QuestionAnswerViewController.swift
🔒 Close #170
🔒 Close #177
- ReviewedArtworkList가 emty일 때, 사용자에게 아직 작성한 작품이 없다는 것을 명시하는 UI 구현했습니다.
이 과정에서 기존의 ErrorView를 조금 변경했고, 디자인 시안에서도 ErrorView의 종류가 다양해져서 ErrorMessage를 수정했습니다.
```swift
enum ErrorViewMessage {
case loadFailed(type: ErrorType)
case noReview
case networkError(type: ErrorType)
}
```
디자인 시안에 따라 에러의 종류를 3개로 나눴습니다.
ErrorMessage가 `.noReview`일 때는 탭하여 다시 시도 버튼이 아니기 때문에 이를 구분할 수 있도록 처리했습니다.
- 유저가 감상 기록을 편집할 수 있도록 했습니다.
새로 update 유즈케이스를 만든 것은 아니고, 기존에 호종이가 만든 add 유즈케이스를 활용했습니다.
- [링크이름](링크)
> [Feature] #170:  유저가 작성한 작품에 대한 리뷰가 없을 때 보여주는 UI 구현했습니다.

- Gom4ziz/Source/Data/Repository/FirebaseArtworkDescriptionRepository.swift
- Gom4ziz/Source/Data/Repository/FirebaseHighlightRepository.swift
- Gom4ziz/Source/Domain/Model/MockData.swift
- Gom4ziz/Source/Presenter/Component/AsyncImageView.swift
- Gom4ziz/Source/Presenter/Component/HighlightedTextView.swift
- Gom4ziz/Source/Presenter/Component/PaddingLabel.swift
- Gom4ziz/Source/Presenter/Component/ZoomableAsyncImageView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewModel.swift
- Gom4ziz/Source/Presenter/MyFeed/UpdateReview/UpdateReviewViewController.swift
- Gom4ziz/Source/Presenter/MyFeed/ZoomableImageViewController.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/ArtworkIntroduction/ArtworkIntroductionModal.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/ArtworkIntroduction/ArtworkIntroductionView.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/ArtworkIntroduction/ArtworkIntroductionViewController.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerPage/QuestionAnswerView.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerPage/QuestionAnswerViewModel.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerPage/QuestionView.swift
- 질문이 더 잘보이도록 작품 사진 위에 반투명한 배경을 추가함
- TextView가 입력한 텍스트에 따라 길어지도록 수정하였음
- 작품 이미지 뒤에 회색 배경을 추가했습니다.
작품 설명 모달의 감상평 작성 텍스트뷰도, 길이에 따라 늘어나도록 했습니다.
더보기 버튼과 설명 사이의 간격을 늘리고, 버튼 클릭 영역을 패딩을 적용해 늘렸습니다.
- 더블 탭 제스쳐로 이미지를 확대할 수 있도록 수정하였습니다.
- 확대 가능한 이미지 뷰의 스케일이 1일 때, 스크롤이 불가능하도록 수정함
- 작품 설명과 하이라이트는, 변경될 가능성이 없음 (하이라이트의 경우 편집이 불가능함) 따라서 캐시를 활용합니다.
- AspectFit 사이즈에 맞추라는 변수가 true일 때, height가 350혹은 width와 height 비율에 맞게 동적으로 변하도록 변경함
- 어떤 Action의 Event를 방출하는 Relay를 Publish로 바꿈.
- [링크이름](링크)
> 리허설 때 나온 피드백 중 대부분을 반영하였습니다.

- Gom4ziz/Source/Domain/Model/ArtworkDescription.swift
- Gom4ziz/Source/Extension/String.swift
- Gom4ziz/Source/Presenter/Main/WeeklyQuestion/MainQuestionView.swift
🔒 Close #192
1) firebase의 ArtworkDescription에 \n이 있을 시 UI에서 개행이 되도록 코드 추가했습니다.
- firebase에서 ArtworkDescription을 등록할 시에 \n을 입력하면 \\n으로 값이 들어가서 UI에서 좌측과 같이 보이게 됩니다. 
그래서 firebase에서 값을 불러왔을 때 \\n을 다시 \n으로 변경하는 코드를 추가함으로 오른쪽 그림처럼 개행이 되도록 변경했습니다.
<table> 
<tr>
<td><img width="251" alt="스크린샷 2022-12-09 오전 5 25 02" src="https://user-images.githubusercontent.com/82457928/206560493-a9fd3e6e-2db9-4846-9fca-4897a96196ca.png"></td>
<td><img width="251" alt="스크린샷 2022-12-09 오전 5 25 58" src="https://user-images.githubusercontent.com/82457928/206560509-2a20d7f8-d6a6-4ed6-b181-a5d99f35f770.png"></td>
</tr>
</table> 
2) firebase에 모든 작품의 ArtworkDescription에 필요한 개행(\n)을 추가해서 재등록했습니다.
@HoJongE ArtworkDescription 내용 다듬어주신 후에 \n\n(2번) …
> feat: firebase의 ArtworkDescription에 \n이 있을 시 UI에서 개행이 되도록 코드 추가
