DeveloperAcademy-POSTECH/MacC_Team_Beartear

- .gitattributes
- pbxproj 충돌 방지를 위해 추가함
- 없음
- 없음
> Docs: Add .gitattributes

- Gom4ziz/Gom4ziz.xcodeproj/project.pbxproj
🔒 Close #3 
- RxSwift, RxCocoa, RxRelay 라이브러리 추가
- Firebase Auth, Firebase Firestore 라이브러리 추가
- 없음
- RxSwift 라이브러리는 많이 쓰일 것 같아서, dynamic 버전으로 import 했습니다. 그러나 dynamic library 와 static library 에 대해 자세히 아는 편이 아니라서, 일단은 앱 용량을 줄이기 위해서 dynamic 버전으로 선택했어요.
- 2022/10/20 19:33 그러나 dynamic library 로 추가하니 라이브러리 링킹 부분이 오류나는거 같아서 다시 static 으로 바꿧어요...
https://zeddios.tistory.com/1308
> 필요한 RxSwift, Firebase 라이브러리를 추가했습니다.

- Gom4ziz/Gom4ziz.xcodeproj/project.pbxproj
- Gom4ziz/Gom4ziz/Domain/Model/MockData.swift
- Gom4ziz/Gom4ziz/Domain/Model/PlansRoom.swift
- Gom4ziz/Gom4ziz/Presenter/PlansRoomList/PlansRoomListViewController.swift
App statement가 "친구 그룹에서 필요한 결정을 쉽고 빠르게 할 수 있도록 도와주자" 이므로 친구와의 간단한 약속에서 발생하는 결정을 도와주는 것이기 때문에 `Promise` 보다 `Plans`가 더 적절하다고 판단했습니다.
🔒 Close #8
- [링크이름](링크)
> PromiseRoom Model의 이름을 변경 PlansRoom으로 변경합니다.

- Gom4ziz/Gom4ziz.xcodeproj/project.pbxproj
🔒 Close #33 
- 키체인 사용 하기 위해서 호종이가 만들어놓은 패키지 사용
없음
없음
> Feat: add keychain package

- Gom4ziz/Source/Data/FirebaseArtworkRepository.swift
🔒 Close #53
- Artwork를 불러오는 기능 구현
- Usecase와 DB의 의존성을 낮추기 위해 ArtworkRepository를 구현하였습니다
- rx를 처음 사용해봐서 해당 부분 몇 줄 안되지만 확인 부탁드립니다.
- 미처 하지 못한 부분이 있다면 가이드 부탁드립니다
- [링크이름](링크)
> Feat: Artwork를 DB에서 불러올 수 있는 repository를 구현했습니다

- Gom4ziz/Source/Data/Repository/FirebaseArtworkReviewRepository.swift
🔒 Close #46
- `ArtworkReview`를 요청하는 기능을 구현했습니다.
- Usecase가 DB에 의존하지 않도록, Data Layer에 추상화 Layer인 `ArtworkReviewRepository`를 만들어 의존하도록 했습니다.
- [링크이름](링크)
> Feat: #46 ArtworkReview를 DB에서 불러오는 기능을 구현했습니다.

- Gom4ziz/Source/Domain/Model/MockData.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerViewController.swift
🔒 Close #62 
- QustionAnswerViewController 진입 시 자동으로 키보드가 올라오는 기능을 추가했습니다.
> 62 [Feature] 질문 답변 작성 화면 진입 시, 자동으로 키보드가 올라오도록 구현한다.

- Gom4ziz/Source/Data/UserRepository.swift
- Gom4ziz/Source/Domain/Model/MockData.swift
- Gom4ziz/Source/Domain/Model/User.swift
🔒 Close #51 
#51 이슈에 작성한 내용입니다 ! 이번 PR에서는 UserRepository 프로토콜 중 addUser만 구현했습니다 :)
- 데이터 구조 중심으로 봐주시면 감사하겠습니다 :)
- [User Id는 identifierForVendor 값으로 하고, 앱을 지웠다 깐 유저는 데이터가 날라간다.](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/discussions/58)
[DB 모델링 I/E 표기법](https://rriver2.notion.site/I-E-7dc0a128efdc4a86968921b933d9eee4)
[firebase data model](https://firebase.google.com/docs/firestore/data-model?hl=ko)
[하위 컬렉션](https://firebase.google.com/docs/firestore/data-model?hl=ko#subcollections)
> feat: User id, lastArtworkId DB에 저장

- Gom4ziz/Source/Data/Repository/FirebaseUserRepository.swift
> [Feature] #74 UserRepository에 DB에서 User를 불러오는 FetchUser() 함수 추가

- Gom4ziz/Source/Data/Repository/FirebaseArtworkRepository.swift
- Gom4ziz/Source/Domain/UseCase/FetchReviewedArtworkUsecase.swift
- Gom4ziz/Source/Extension/RxSwift+Firestore.swift
🔒 Close #80 
이번 PR에서는 하단의 이미지에 있는 FetchReviewedArtworkUsecase와 ArtworkRepository를 구현했습니다.
DB에서 Review된 Artwork들을 불러오기 위해서 FetchReviewedArtworkUsecase에서 ArtworkRepository의 fetchReviewedArtworkList(lastArtworkId)을 호출하여, ReviewedArtworkList를 반환 받는 코드를 작성했습니다.
**[고민사항]**
lastArtworkId 값을 넣는 부분은 후에 레이몬드와 좀 더 상의를 해봐야할 것 같습니다.
위 View에서 질문 나오는 컴포넌트와 리뷰한 작품들을 보여주는 컴포넌트를 같은 Viewmodel을 쓰고 그 Viewmodel 안에 lastArtworkId을 저장해두고 공유해서 사용할지, 
아니면 두 컴포넌트의  Viewmodel을 분리할지 고민 중에 있습니다. 후자의 경우에는 어떻게 데이터를 가져와야 하는지 머릿속에 그려지지가 않습니다.. 저와 토론해주실 @SH0123 구합니다. 
- 데이터 구조, naming 중심으로 봐주세요..!
**[질문]**
작동하는지 테스트 한다고 firebase에 값 넣어놨는데 삭제해야 하나요 ?
[Firebase collection 에서 필요한 …
> [Feature] #80: DB에서 Review된 ArtworkList를 불러온다

- .swiftlint.yml
- Gom4ziz/Source/Extension/UIImageView.swift
- Gom4ziz/Source/Presenter/Component/AsyncImageView.swift
- Gom4ziz/Source/Utility/ImageCacheManager.swift
🔒 Close #91 
- http url을 통해 이미지를 비동기적으로 불러오는 AsyncImageView를 구현했습니다.
- 디스크 캐시를 이용하므로, 한 번 이미지를 웹에서 불러온 뒤론 디스크에서 불러오게 됩니다.
- AsyncImageView의 존재가 있다는 것을 알아주셨으면 합니다...
- [fileManager를 사용해 이미지 데이터를 disk에 저장하기](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:Feat%2F%2391_async_image?expand=1&title=Add%3A%20Async%20Image%20View&body=%23%23%20Close%20Issues%0A-%20Pull%20Request와%20관련된%20Issue가%20있다면%20나열합니다.%0A%F0%9F%94%92%20Close%20%23number%0A%0A%23%23%20작업%20내용%20(Content)%0A-%20작업한%20내용을%20나열%20후%20설명%0A%0A%23%23%20Review%20points%0A-%20리뷰어가%20중점적으로%20리뷰해줬으면%20하는%20포인트%0A%0A%23%23%20기타%20사항%20(Etc)%0A-%20작업하면서%20고민이%20되었던%20부분이나%20질문%20사항%20등%0A%0A%23%23%20관련%20사진%20gif%20및%20(Optional)%0A%0A%23%23 …
> HTTP 요청을 통해 이미지를 비동기적으로 불러오는 AsyncImageView를 추가했습니다.

- Gom4ziz/Source/Data/Repository/FirebaseUserRepository.swift
- Gom4ziz/Source/Domain/UseCase/FetchUserUsecase.swift
- Gom4ziz/Source/Presenter/MyFeed/UserViewModel.swift
🔒 Close #74
1) UserViewModel, FetchUserUsecase, FetchUserUsecase에 있는 User정보를 불러오는 함수명이 다 fetchUser()로 같습니다. 각 기능에 맞게 이름이 변경되어야 할 거 같은데 어떻게 naming을 하면 좋을지 감이 오지 않습니다. HELP ME PLEASE ~!
2) 아래 코드 부분 xcode로 작업할 때는 DB에 UserId가 "mock"인 걸로 확인하고 있어서, 전처리문을 사용해 DEBUG 일 때와 아닐때로 나눠놨습니다. 이 부분도 CollectionName과 비슷하게 DEBUG일때 아닐때로 나눠서 값을 불러오는 코드를 따로 빼야 하는지 고민했는데 그냥 둬도 괜찮을까요?
```
#if DEBUG
return "mock"
#else
return UIDevice.current.identifierForVendor!.uuidString
#endif
```
3) issue를 꼼꼼하게 작성하다보니 issue와 PR 설명이 겹치는 부분이 많은데 이 PR처럼 issue에 있는 거 복붙해서 올린 걸 보시는게 편하신가요? 아니면 issue 확인해달라고 링크를 달아놓는게 편하실까요 ?
- [고민이 되었던 부분] : UserViewmodel을 Singleton으로 구현하는 것 : [discussion](https://github.com/DeveloperAcademy-POSTECH/MacC_Team …
> feat: #74 SceneDelegate에서 User 정보를 DB에서 불러오는 Viewmodel 구현

- Gom4ziz/Source/Domain/Model/ArtworkReview.swift
- Gom4ziz/Source/Domain/Model/MockData.swift
- Gom4ziz/Source/Domain/Model/QuestionAnswer.swift
🔒 Close #99
-> #99 해당 issue를 확인해주세요
-> 이 부분은 @SH0123 가 요청해서 변경하게 되었습니다. 관련 해서 고민했던 내용 작성 부탁드려요 ~
> refact: #99 hifi에 따른 entity가 변경되었습니다. (questionAnswer 추가, timeStamp 타입 Date -> Int)

- Gom4ziz/Source/Presenter/Main/MainView.swift
- Gom4ziz/Source/Presenter/Main/MainViewController.swift
🔒 Close #105
- MainViewController와 MainView를 미리 만들었습니다
-  각자 QuestionView랑 ArtworkHistoryView 만들어서 MainView안에 넣어주면 되는거죠?
- [링크이름](링크)
> [Feature] #105 리버와 함께 사용할 MainViewController와 MainView를 충돌을 피하기 위해서 미리 만들었습니다

- .swiftlint.yml
- 기존에 빌드 시, 외부 패키지 파일까지 모두 린트하느라 생각보다 린트에 시간이 엄청 많이 소요되는 것 같았어요.
- 그래서 우리 앱 타겟, 테스트 타겟만 린트가 적용되도록 린트 파일을 수정했습니다!
- 항상 린트 워닝을 없애도록 노력합시다! 본인이 만든 린트 워닝이나 에러는 본인이 수정하는 원칙을 세워봐요 
- [린트 사용법](https://github.com/realm/SwiftLint/blob/main/README_KR.md)
> 앱, 테스트 타겟만 린트할 수 있도록 린트 파일을 수정했습니다!

- Gom4ziz/Source/Domain/Model/Error.swift
- Gom4ziz/Source/Presenter/Component/OnBoardingButton.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingFirst/OnBoardingFirstView.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingFirst/OnBoardingFirstViewController.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingPageViewController.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingSecond/OnBoardingSecondView.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingSecond/OnBoardingSecondViewController.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingThird/OnBoardingThirdView.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingThird/OnBoardingThirdViewController.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingViewController.swift
- Gom4ziz/Source/Presenter/WeeklyArtworkStatus.swift
- Gom4ziz/Source/System/SceneDelegate.swift
🔒 Close #47
- 리뷰 포인츠에 고민 부분을 많이 작성해뒀습니다. 확인하고 답변 달아주시면 감사하겠습니다
- onBoarding은 UIPageViewController 사용할 생각입니다. 
- userViewModel을 sceneDelegate에서 어떻게 사용해야할지 모르겠어서 일단 사용해봤습니다
- [sceneDelegate에서는 다른 viewController들처럼 vc가 사라지고, 메모리가 누수되는 일이 없다고 판단되어 weak self를 사용하지 않았습니다](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/114/files#diff-71b56716bbcc7052c5097b24226437d5aa0d8b9e72bed595881e391b10935064R31-R48)
- [위와 같은 이유로 disposeBag을 사용하는것도 필요할지 의문이 듭니다. disposed(by:) 부분을 빼도 될까요?](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/114/files#diff-71b56716bbcc7052c5097b24226437d5aa0d8b9e72bed595881e391b10935064R50-R51)
- [user를 불러오는 상황에서 처음 앱에 가입하여 유저가 서버에 없는 경우도 error가 발생할거라고 생각했습니다. 이 상황은 다른 error와 구분이 필요할 것 같아 따로 에러 상태를 …
> [Feature] #47 sceneDelegate 설정, 온보딩에 필요한 component,  viewController, view 파일 추가

- Gom4ziz/Source/Presenter/Component/HighlightedTextView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
🔒 Close #113
- 이전에는 MyFeedView에서 작품 설명과 하이라이트 부분을 불러와서 유저에게 보여주는 부분을 UILabel을 이용해 커스텀으로 만들었었습니다.
- @HoJongE 이 만들어준 Component인 HighlightTextView 사용하여 해당 부분을 리팩토링했습니다.
- 그 과정에서 HighlightTextView의 오토레이아웃 부분에서 버그를 발견해서 해당 부분을 해결했습니다.
[HighlightTextView의 오토레이아웃 부분에서 버그](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/discussions/119)
- [링크이름](링크)
> [Refactor] #113: HighlightTextView를 MyFeedView에 추가하여 리팩토링했습니다.

- Gom4ziz/Source/Domain/Model/Error.swift
- Gom4ziz/Source/Domain/UseCase/RequestNextArtworkUsecase.swift
- Gom4ziz/Source/Extension/UIButton+TextStyle.swift
- Gom4ziz/Source/Presenter/Component/OnBoardingButton.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingFirst/OnBoardingFirstView.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingFirst/OnBoardingFirstViewController.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingPageViewController.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingSecond/OnBoardingSecondViewController.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingThird/OnBoardingThirdViewController.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingViewController.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingViewModel.swift
- Gom4ziz/Source/Presenter/QuestionViewModel.swift
- Gom4ziz/Source/System/SceneDelegate.swift
- Gom4zizTests/Source/DateHelperTests.swift
- Gom4zizTests/Source/RequestNewArtworkUsecaseTest.swift
🔒 Close #50 
🔒 Close #48
- UIPageViewController를 구현하여 onBoarding을 만들고 있습니다
- [온보딩의 뷰가 슬라이드 되는동안 버튼은 그 자리를 유지하면 좋겠다는 디자인 요구사항에 맞추기 위해 OnBoardingViewController에 OnBoardingButton과 OnBoardingPageViewController를 자식으로 넣어줬습니다](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/126/files#diff-c8d0eab123a10b698555961384ec4f8a8e7d7f66cedd119404f57900637391e0R65-R86)
- [현재 페이지 인덱스를 알기 위해서 currentPageIndex를 포함하는 viewModel을 만들었으며, OnBoardingPageViewController와 OnBoardingViewController에서 같은 값에 대한 접근이 필요하여 싱글톤으로 만들었습니다 (단지 두개의 viewController에서 사용하는 observable이라면 싱글톤보다 파라미터로 넘겨주는게 더 좋을까요? 싱글톤 패턴은 웬만하면 피하는게 좋다는 글을 봤습니다)](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/126/files#diff-391186b4ebe3b99ad72fe80133c95b3f49b9cfc47d5ec8cae8 …
> [Feature] #50 온보딩 공통 버튼을 만들었으며 UIPageViewController를 구현했습니다

- Gom4ziz/Source/Presenter/ArtworkIntroduction/ArtworkIntroductionModal.swift
- Gom4ziz/Source/Presenter/ArtworkIntroduction/ArtworkIntroductionView.swift
- Gom4ziz/Source/Presenter/ArtworkIntroduction/ArtworkIntroductionViewController.swift
- Gom4ziz/Source/Presenter/Component/ZoomableAsyncImageView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
- Gom4ziz/Source/Presenter/QuestionAnswer/QuestionAnswerViewModel.swift
- Gom4ziz/Source/Utility/UIViewTestHelper.swift
🔒 Close #121 
- ArtworkIntroduction modal이, 자체적으로 화면 크기를 계산한 후 화면 아래쪽에 위치하도록 리팩토링하였습니다.
- ArtworkIntroduction modal에 드래그 제스처를 추가해, 자체적으로 슈퍼뷰 안에서 위치를 조정하도록 리팩토링하였습니다.
- Zoom 가능한 AsyncImageView 컴포넌트를 구현했습니다.
- ArtworkIntroductionView를 구현했습니다.
- [Modal에 Pan Gesture Recognizer를 추가해서, 유저 드래그 정보를 얻어오는 부분](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:feat%2F%23121_artwork_introduction_u?expand=1&title=121%20%5BFeature%5D%3A%20작품%20소개%20UI를%20구현합니다.#diff-3e59a348ba2a0f7c79914b8c3940750b91ddaa15f1cc620bc2f3ae9575aedd9cR276-R363)
- [유저가 작품 설명 ScrollView를 계속해서 위로 스크롤 할 경우, 모달이 닫히도록 구현했습니다!](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:feat%2F%23121_artwork_introduction_u?expand=1& …
> 작품 소개 UI를 구현했습니다.

- .swiftlint.yml
- Gom4ziz/Source/Domain/Model/MockData.swift
- Gom4ziz/Source/Presenter/Main/ReviewedArtworkList/ReviewedArtworkCell.swift
🔒 Close #132
- ReviewedArtworkCell을 구현했습니다. 아래 이미지에는 tableView 캡쳐본이 있는데 Cell만 확인해주시면 될거 같아요 ~ 🌷
- 오토레이아웃이나 lable, imageView setUpUI 하는 부분에서 빠트린 게 있는지 확인 부탁드립니다 🙏🏻🥹
-> ~~fontSize를 제대로 넣은 거 같은데,, 시뮬레이터로 돌린 뷰의 font size, image 크기가 더 크게 나와서.. 뭐가 문제인지 못 찾고 있습니다..~~ (레몬이 해결해주심 !)
@HoJongE 
cell을 set할 때 받아오는 파라매터 값을 AsyncImageView에 넣어주기 위해서 run time에 AsyncImageView의 값이 달라질 수 있도록 하는 함수를 구현해주시기로 했었는데, Cell이 init 될 때 들어가는 AsyncImageView도 있으면 좋을 것 같습니다.
> [Feat]: 리뷰된 작품을 확인하는 tableView의 ReviewedArtworkCell UI를 구현합니다. 

- Gom4ziz/Source/Constants/Typography.swift
- Gom4ziz/Source/Extension/UIViewController+Loadble.swift
- Gom4ziz/Source/Presenter/Component/ErrorView.swift
- Gom4ziz/Source/Presenter/Component/HighlightedTextView.swift
- Gom4ziz/Source/Presenter/Component/LoadingView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedViewModel.swift
🔒 Close #125
- 감상 기록 화면 전반적인 로직입니다.
- <img width="1018" alt="Screenshot 2022-11-29 at 13 09 30" src="https://user-images.githubusercontent.com/59136391/204439058-b9ca39a6-aa16-41ff-afc0-79088d65b68d.png">
- 유저가 감상 기록으로 들어가면 DB에서 ArtworkDescription, Highlight, ArtworkReview를 불러오고, 
데이터가 요청되는 동안은 `LoadingView`를 보여주고, 데이터 요청이 성공하면 View를 잘 보여주고, 실패하면 `ErrorView`를 보여줄 수 있게 했습니다.
- 데이터 요청이 실패하여 ErrorView가 나타내게 되면, `탭하여 다시 시도`버튼을 눌러 데이터를 다시 요청할 수 있습니다.
- 이 과정을 편하게 사용할 수 있도록 UIViewControler+Extension으로 새로 만들었습니다.
```swift
setUpLoadigView(_: LoadingView)
removeLoadingVIew(_: LoadingView)
setUpErrorView(_: ErrorView)
removeErrorView(_: ErrorView)
```
---
<div style="display: flex; justify-content: center; align-items: center">
</div>
- @HoJongE 가 제안해준 …
> [Feature] #125: 감상 기록 화면에서 데이터 요청 결과에 따른 UI를 구현했습니다.

- Project.swift
🔒 Close #144 
- Tuist 프로젝트 파일에 Lottie 의존성을 추가했습니다.
> 로티 라이브러리를 추가했습니다.

- Gom4ziz/Source/Extension/UIViewController+ErrorAlert.swift
- Gom4ziz/Source/Extension/UIViewController+Toast.swift
- Gom4ziz/Source/Presenter/Component/ToastView.swift
- Gom4ziz/Source/System/SceneDelegate.swift
- Gom4ziz/Source/Utility/UIViewTestHelper.swift
🔒 Close #160 
- Toast Message를 보여줄 수 있는 UI를 구현했습니다.
- 해당 Toast Message는 지정한 duration (기본값은 3)초 후에 자동으로 사라집니다.
- 화면(ViewController)을 이동하더라도 사라지지 않게끔, 최상단 window에 ToastView를 추가하도록 구현했습니다.
- Toast 메시지를 쉽게 보여줄 수 있도록, UIViewController에 extension을 추가했습니다.
- 단순히 showToastMessage만 호출하면, 알아서 Toast 메시지를 보여주고 알아서 사라집니다!
```swift
func showToastMessage(
text: String,
duration: TimeInterval = 3,
textAlignment: NSTextAlignment = .center
) {
let scenes = UIApplication.shared.connectedScenes
let windowScene = scenes.first as? UIWindowScene
guard let window = windowScene?.windows.first else { return }
let toastView: ToastView = ToastView(text: text, duration: duration, alignment: textAlignment)
window.addSubview(toastView)
toastView.translatesAutoresizingMaskIntoConstraints = false …
```
> Toast UI를 구현하고, 쉽게 사용할 수 있도록 extension을 추가했습니다.

- Gom4ziz/Source/Presenter/Main/ReviewedArtworkList/ReviewedArtworkCell.swift
🔒 Close #180 
- ReviewedArtworkCell에서 사용되는 AsyncImageView 이미지를 호종이가 구현해놓은 함수로 런타임에서 바뀔 수 있도록 수정했습니다.
> refac: ReviewedArtworkCell에서 사용되는 AsyncImageView 이미지 변경 가능하게 수정

- Gom4ziz/Source/Constants/ErrorViewMessage.swift
- Gom4ziz/Source/Presenter/Main/ReviewedArtworkList/MainViewController.swift
🔒 Close #178
- reviewdArtworkCellList를 load할 때 fail시 #124에서 만들어 둔 ErrorView를 보여줍니다.
[[Feature] #123: DB에서 데이터를 불러오는데 실패했을 때, 보여줄 ErrorView를 추가했습니다.](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/124)
> [Feat]: reviewdArtworkCellList를load할 때 fail시 error처리

- Gom4ziz/Source/Presenter/Main/ReviewedArtworkList/MainViewController.swift
🔒 Close #number
- 네비게이션바에 mainViewController가 가려지는 문제 해결
- [링크이름](링크)
> [Hotfix] 네비게이션바에 mainViewController가 가려지는 문제 해결

- Gom4ziz/Source/Presenter/Main/WeeklyQuestion/MainQuestionView.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingPageViewController.swift
- Gom4ziz/Source/Presenter/OnBoarding/OnBoardingViewModel.swift
🔒 Close #number
- 온보딩에서 크래쉬 나는 문제를 해결했습니다
- main view controller에서 question label의 글자 height가 적용되지 않는 문제를 해결했습니다
- [링크이름](링크)
> [HotFix] 온보딩 에러 수정 및 글자 lineHeight 수정

- Gom4ziz/Resource/GoogleService-Info.plist
- Gom4ziz/Source/Presenter/Component/AsyncImageView.swift
- Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
🔒 Close #number
- 번들ID 변경으로 인한 파이어베이스 infoPlist 추가했습니다.
- 감상기록 화면에서 질문의 right 오토레이아웃이 적용이 안되어있는 버그를 수정했습니다.
- AsyncImageView의 maxHeight를 제거했습니다.
- [링크이름](링크)
> [Fix] : 번들ID 변경으로 인한 파이어베이스 infoPlist 추가 및 UI 버그를 수정했습니다.
